# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
language: ruby
rvm:
  - 1.9.3
  - 2.0.0

before_install:
  - gem update bundler

matrie:
  allow_failures:
    - rvm: 1.9.3
    - rvm: 2.0.0

script: "RAILS_ENV=test bundle exec rake spec 2>&1"
